#!/bin/zsh

set -o vi

export ZSH="$HOME/.oh-my-zsh"
plugins=(zsh-completions zsh-autosuggestions zsh-syntax-highlighting)
ZSH_THEME="simple"
source $ZSH/oh-my-zsh.sh

. "$HOME/.zsh-aliases"
# . "$HOME/.zsh-envs"

# Vars

export EDITOR=nvim

# Path

PATH=$PATH:~/dev/scripts
# . "$HOME/.cargo/env"

export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:/usr/local/go/bin:$PATH

[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"

# pnpm
export PNPM_HOME="/home/yuta/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# bun completions
[ -s "/home/yuta/.bun/_bun" ] && source "/home/yuta/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

export PATH="$PATH:/home/yuta/dev/flutter/bin"
