#!/bin/zsh

# --color=auto
alias ls="ls --color=auto"
alias grep="grep --color=auto"
alias diff="diff --color=auto"

# -i
alias md="mkdir"
alias mv="mv -i"
alias rm="rm -i"
alias rmrf="rm -rf"
alias cp="cp -i"

# commands
alias ..="cd .."
alias ..2='cd ../..'
alias ..3='cd ../../..'
alias ..4='cd ../../..'
alias ..5='cd ../../..'
alias cl="clear"

# apt
alias apt="sudo apt"
alias ai='sudo apt install'
alias ar='sudo apt remove'
alias au="sudo apt update"
alias upgrade="sudo apt update && sudo apt upgrade"

# vim
alias vim="nvim"

# git
alias g="git"
alias ga="git add"
alias gc="git commit"
alias gb="git branch"
alias gd="git diff"
alias gs="git status"
alias gp="git push"
alias gf='git fetch'
alias gco='git checkout'
